- hosts: grafana

  vars_files:
    - "{{ raw }}/raw_docker/var.yml"

  tasks:

  - name: Template a file to grafana
    template:
      src: "{{ raw }}/raw_docker/grafana/{{ item }}.j2"
      dest: /home/{{ ansible_user }}/{{ item }}.yml
      owner: "{{ ansible_user }}"
      mode: '0660'
    loop:
      - datasources
      - grafana
      - main

  - name: Run
    command: 
      cmd: docker compose -f /home/{{ ansible_user }}/grafana.yml up -d 

  - name: Copy a file 
    copy:
      src: "{{ raw }}/raw_docker/grafana/{{ item }}.json"
      dest: /home/{{ ansible_user }}/grafana-dashboards/prometheus/{{ item }}.json
      owner: "{{ ansible_user }}"
      mode: '0660'
    loop:
      - nginx
      - node-exporter

