- hosts: kibana

  vars_files:
    - "{{ raw }}/raw_docker/var.yml"

  tasks:

  - name: Template a file to "{{ ansible_hostname }}"
    template:
      src: "{{ raw }}/raw_docker/kibana/{{ item }}.j2"
      dest: /home/{{ ansible_user }}/{{ item }}.yml
      owner: "{{ ansible_user }}"
      mode: '0660'
    loop:
      - kibana

  - name: Run DC
    command: 
      cmd: docker compose -f /home/{{ ansible_user }}/kibana.yml up -d
  