- hosts: prometheus 

  vars_files:
    - "{{ raw }}/raw_docker/var.yml"


  tasks:

  - name: Template a file 
    template:
      src: "{{ raw }}/raw_docker/prometheus/{{ item }}.j2"
      dest: /home/{{ ansible_user }}/{{ item }}.yml
      owner: "{{ ansible_user }}"
      mode: '0660'
    loop:
      - prometheus
      - prometheus-docker


  - name: Run DC
    command: 
      cmd: docker compose -f /home/{{ ansible_user }}/prometheus-docker.yml up -d
